### ISSUE TITLE
Application error when opening Sutta Study Window

### ISSUE THREAD

**Issue by thesunshade** [simsapa/simsapa#4]
System: Windows 10

When trying to `Window > Sutta Study` from a `Sutta Search` window, I get the following error:

```
Traceback (most recent call last):
  File "C:\GitHub\simsapa\simsapa\app\windows.py", line 191, in _new_sutta_study_window
    view = SuttaStudyWindow(self._app_data)
  File "C:\GitHub\simsapa\simsapa\layouts\sutta_study.py", line 46, in __init__
    self.search_query = SearchQuery(
  File "C:\GitHub\simsapa\simsapa\app\db\search.py", line 112, in __init__
    self.searcher = ix.searcher()
  File "C:\Users\learningtoletgo\AppData\Local\pypoetry\Cache\virtualenvs\simsapa-Tw4STD9V-py3.9\lib\site-packages\whoosh\index.py", line 318, in searcher
    return Searcher(self.reader(), fromindex=self, **kwargs)
  File "C:\Users\learningtoletgo\AppData\Local\pypoetry\Cache\virtualenvs\simsapa-Tw4STD9V-py3.9\lib\site-packages\whoosh\index.py", line 547, in reader
    return self._reader(self.storage, info.schema, info.segments,
  File "C:\Users\learningtoletgo\AppData\Local\pypoetry\Cache\virtualenvs\simsapa-Tw4STD9V-py3.9\lib\site-packages\whoosh\index.py", line 535, in _reader
    readers = [segreader(segment) for segment in segments]
  File "C:\Users\learningtoletgo\AppData\Local\pypoetry\Cache\virtualenvs\simsapa-Tw4STD9V-py3.9\lib\site-packages\whoosh\index.py", line 535, in <listcomp>
    readers = [segreader(segment) for segment in segments]
  File "C:\Users\learningtoletgo\AppData\Local\pypoetry\Cache\virtualenvs\simsapa-Tw4STD9V-py3.9\lib\site-packages\whoosh\index.py", line 523, in segreader
    return SegmentReader(storage, schema, segment,
  File "C:\Users\learningtoletgo\AppData\Local\pypoetry\Cache\virtualenvs\simsapa-Tw4STD9V-py3.9\lib\site-packages\whoosh\reading.py", line 620, in __init__
    self._terms = self._codec.terms_reader(self._storage, segment)
  File "C:\Users\learningtoletgo\AppData\Local\pypoetry\Cache\virtualenvs\simsapa-Tw4STD9V-py3.9\lib\site-packages\whoosh\codec\whoosh3.py", line 122, in terms_reader
    postfile = segment.open_file(storage, self.POSTS_EXT)
  File "C:\Users\learningtoletgo\AppData\Local\pypoetry\Cache\virtualenvs\simsapa-Tw4STD9V-py3.9\lib\site-packages\whoosh\codec\base.py", line 556, in open_file
    return storage.open_file(fname, **kwargs)
  File "C:\Users\learningtoletgo\AppData\Local\pypoetry\Cache\virtualenvs\simsapa-Tw4STD9V-py3.9\lib\site-packages\whoosh\filedb\filestore.py", line 333, in open_file
    return self.a.open_file(name, *args, **kwargs)
  File "C:\Users\learningtoletgo\AppData\Local\pypoetry\Cache\virtualenvs\simsapa-Tw4STD9V-py3.9\lib\site-packages\whoosh\filedb\compound.py", line 121, in open_file
    f = BufferFile(buf, name=name)
  File "C:\Users\learningtoletgo\AppData\Local\pypoetry\Cache\virtualenvs\simsapa-Tw4STD9V-py3.9\lib\site-packages\whoosh\filedb\structfile.py", line 357, in __init__
    self.file = BytesIO(buf)
MemoryError

```
Simsapa 0.1.8-alpha.1
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)], Qt 5.15.2, PyQt 5.15.6

I get an error if I try to open the window from the menu bar or with the shortcut.

I tried restarting the app and still got the error.

**Comment by gambhiro** [comment]
Did adjusting your pagefile.sys settings solve this?

There is a Windows exe now at [v0.1.9-alpha.1](https://github.com/simsapa/simsapa/releases/tag/v0.1.9-alpha.1), try if that works.

**Comment by thesunshade** [comment]
It seems to have. Thanks! I won't mess with that again.
